# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    echo Setting up depot_tools
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  displayName: Setup
  timeoutInMinutes: 0

- script: |
    echo Syncing sources
    set -ex
    export PATH=$PATH:${PWD}/depot_tools
    fetch --nohooks webrtc_ios
    gclient sync
    (cd src; git checkout c2c150bdf3a30d669b0d975e82c0829011888fa3)
    gclient sync
  displayName: Sync sources
  timeoutInMinutes: 0

- script: |
    echo Patching
    set -ex
    cd src
    for file in ../patches/*; do
      patch -p1 -i "$file"
    done
  displayName: Patching
  timeoutInMinutes: 0

- script: |
    echo Preparing source tree
    set -ex
    export PATH=$PATH:${PWD}/depot_tools
    cd src
    for arch in arm arm64 x86 x64; do
      gn gen out/ios_${arch} --args='target_os="ios" ios_enable_code_signing=false target_cpu="'"${arch}"'"'
    done
  displayName: Preparing
  timeoutInMinutes: 0

- script: |
    echo Building
    set -ex
    export PATH=$PATH:${PWD}/depot_tools
    cd src
    for arch in arm arm64 x86 x64; do
      ninja -C out/ios_${arch} socketrocket
      ninja -C out/ios_${arch} rtc_sdk_objc
      ninja -C out/ios_${arch} apprtc_common
      ninja -C out/ios_${arch} apprtc_signaling
    done
  displayName: Building
  timeoutInMinutes: 0

- script: |
    set -ex
    mkdir -p tmp-output ${BUILD_ARTIFACTSTAGINGDIRECTORY}/libs ${BUILD_ARTIFACTSTAGINGDIRECTORY}/headers"
    for arch in arm arm64 x64; do
      cp src/out/ios_${arch}/obj/libwebrtc.a  tmp-output/libwebrtc-${arch}.a"
    done
    lipo -create tmp-output/*  -output ${BUILD_ARTIFACTSTAGINGDIRECTORY}/libs/libwebrtc.a"
    find src -name "*.h" -print | tar --create --files-from - | (cd ${BUILD_ARTIFACTSTAGINGDIRECTORY}/headers && tar xvfp -)
  displayName: Bundle
  timeoutInMinutes: 0

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: webrtc
