# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    echo Setting up depot_tools
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  displayName: Setup

- script: |
    echo Syncing sources
    export PATH=$PATH:${PWD}/depot_tools
    fetch --nohooks webrtc_ios
    gclient sync
    (cd src; git checkout c2c150bdf3a30d669b0d975e82c0829011888fa3)
    gclient sync
  displayName: Sync sources

- script: |
    for file in patches/*; do
      patch -p1 -i "$file"
    done
  displayName: Patching

- script: |
    echo Preparing source tree
    export PATH=$PATH:${PWD}/depot_tools
    gn gen out/ios_arm --args='target_os="ios" ios_enable_code_signing=false target_cpu="arm"'
    gn gen out/ios_arm64 --args='target_os="ios" ios_enable_code_signing=false  target_cpu="arm64"'
    gn gen out/ios_x86 --args='target_os="ios" ios_enable_code_signing=false target_cpu="x86"'
    gn gen out/ios_x64 --args='target_os="ios" ios_enable_code_signing=false target_cpu="x64"'
  displayName: Preparing

- script: |
    echo Building
    for arch in arm arm64 x86 x64; do
      ninja -C out/ios_${arch} socketrocket
      ninja -C out/ios_${arch} rtc_sdk_objc
      ninja -C out/ios_${arch} apprtc_common
      ninja -C out/ios_${arch} apprtc_signaling
    done
  displayName: Building